version: '3.7'

volumes:
    mysite.db.volume:
        name: mysite.db.volume

services:
    nginx:
        image: nginx:1.15
        container_name: mysite.nginx
        ports:
            - "8000:8000"
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
            - ./static:/static
        depends_on:
            - web

    db:
        image: mysql:8.0
        container_name: mysite.db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mysite
            MYSQL_USER: djangouser
            TZ: 'Asia/Tokyo'
        volumes:
            - mysite.db.volume:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        command: mysqld --default-authentication-plugin=mysql_native_password

    web:
        build: ./web
        container_name: mysite.web
        command: uwsgi --ini /code/mysite/django.ini
        volumes:
            - ./src:/code
            - ./static:/static
        expose:
            - "8001"
        depends_on:
            - db

